### ISSUE TITLE
Hello there. I have a question about your language.

### ISSUE THREAD

**Issue by jorge-jbs** [jungerstein/mundolinguo#1]
I've been reading your project and it's very interesting. I found something that I don't really understand. What's the sound of the letter `ñ`? I'm Spanish and I know that it comes from Spanish, but it doesn't look like it's the same sound. Also, what's the difference between j and y?

Thanks a lot for reading this :)

Keep up the great work!

**Comment by jungerstein** [comment]
Thanks for your attention. In my design at this moment, I assign the letter ñ as either (1) Spanish ñ, French gn or Italian gn; (2) English or German ng. Either pronunciation is acceptable. In words currently designed, it seems that the letter transcripts English / German ng, or Chinese -ng sounds more; in Chinese words imported in this project, the initial ñ has been dropped in modern mandarin speech, but it was there a thousand years ago, and still remains in certain dialects (as well as borrowed words in Japanese and Korean). 

The letter j comes from Esperanto, and denotes the sound of J in German Jahr (to me, much like Y in Spanish yo). The letter y denotes the sound ü in German über, and u in French rue. It is mainly for words from Chinese, as well as ones from some other languages with the native y sound. 

I will accomplish the descriptions of pronunciation. In principle, the letters looking the same in Esperanto will read the same as in Esperanto. 

The further target might be a TTS engine / a wrapper of TTS engines (e.g. festival) for the language.

**Comment by jungerstein** [comment]
Thanks @ElGoreLoco ; the pronunciation guide is supplied.
